### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by ydv0121** [WrathChaos/react-native-bouncy-checkbox#158]
After importing the `import BouncyCheckbox from "react-native-bouncy-checkbox";` got below error on render

`"react-native": "0.61.5"`

![Screenshot 2022-10-07 at 1 40 04 PM](https://user-images.githubusercontent.com/37238045/194505276-e89464b8-6366-4758-b1d7-f69d42f6c5b3.png)

**Comment by WrathChaos** [comment]
Hello @ydv0121 
Thank you for reporting this :) 

I just published `3.0.5` version of the library. Can you try this version? 

It seems it works without any problem on `example` project

**Comment by ydv0121** [comment]
Thanks for prompt response.

I updated it to `3.0.5` still facing same.

if I downgrade it to `2.1.13` its working without any issue with `"react-native": "0.61.5"`

and yes it working fine with `example` project which has `RN Version 69` so I think issue is related to `"react-native"`

**Comment by WrathChaos** [comment]
Hmmm, Actually `0.61.5` is really low react-native version. 

I will create a 61.5 version and try to fix it but I'm not promising anything since it is pretty low version of react native

**Comment by ydv0121** [comment]
Right.
So people who are using older RN Version probably lower then `0.65` should use `v2.1.13`
